name: test-coverage

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      # Generate Cobertura XML coverage file
      - name: Compute coverage
        run: |
          cov <- covr::package_coverage()
          xml <- covr::to_cobertura(cov)
          xml2::write_xml(xml, "cobertura.xml")
        shell: Rscript {0}


      # Upload to Codecov using your repository secret
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          fail_ci_if_error: true

      # (Optional) keep these two for easier debugging
      - name: Show testthat output
        if: always()
        run: |
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results (if failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
